------------------------------------------
Running Starter Tests
Starter Tests: 14/14 passed.
----
Starter Tests Mark: 3.00/3
------------------------------------------

------------------------------------------
Running Hidden Tests
Hidden Correctness Tests Part 1: 11/13 passed.
Hidden Correctness Tests Part 2: 1/2 passed
Overall Hidden Tests: 12/15
----
Hidden Tests Mark: 4.80/6
------------------------------------------

------------------------------------------------------------------------------------
Correctness Mark Overall: 7.80/9.
------------------------------------------------------------------------------------
